#' @title deepTimeHePlot
#'
#' @description
#' Produces a ggplot2 of the cumulative amount of helium produced by samples over the specified geologic time in the deepTimeProd() model.
#'
#' @details
#' Takes in the resulting dataframe from deepTimeProd() function and plots the cumulative amount of helium generated by the sample over the duration of the model. Can plot an optional geom_ribbon() around the min/max of the Monte Carlo model.
#'
#' @param deepTimeProdDF Structured dataframe that is the result of the deepTimeProd() function
#' @param ribbon Optional geom_ribbon() around the min/max of the Monte Carlo model
#'
#' @examples
#' data("monteDataLithCat")
#' df <- monteProd(lithCat,1000)
#' dfTime <- deepTimeProd(df,1,100,1)
#' deepTimeH2Plot(dfTime)
#'
#' @export
deepTimeHePlot <- function(deepTimeProdDF,ribbon=FALSE){
  deepTimeProdDF <- arrange(deepTimeProdDF,desc(time))
  deepTimeProdDF$HeMinProdCum <- ave(deepTimeProdDF$HeMinProd, deepTimeProdDF$Sample, FUN=cumsum)
  deepTimeProdDF$HeMeanProdCum <- ave(deepTimeProdDF$HeMeanProd, deepTimeProdDF$Sample, FUN=cumsum)
  deepTimeProdDF$HeMaxProdCum <- ave(deepTimeProdDF$HeMaxProd, deepTimeProdDF$Sample, FUN=cumsum)
  if(ribbon==FALSE){
    ggplot(deepTimeProdDF) + geom_line(mapping=aes(x=time,y=HeMeanProdCum,color=as.factor(Sample))) +
      theme_bw() +
      labs(x="Age (Ma)",y="Cumulative He production of modeled samples - per km3 of source rock") +
      scale_x_reverse() +
      scale_y_continuous(sec.axis=sec_axis(~.*4.0026/1000, name="Mass (kg)"))
  } else {
    ggplot(deepTimeProdDF) +
      geom_line(mapping=aes(x=time,y=HeMeanProdCum, color=Sample)) +
      geom_ribbon(mapping=aes(x=time,ymin=HeMinProdCum,ymax=HeMaxProdCum, fill=Sample),alpha=0.1) +
      theme_bw() +
      labs(subtitle="Cumulative He production of modeled samples - per km3 of source rock",
           x="Age (Ma)",
           y="He production (mols/km3)") +
      scale_x_reverse() +
      scale_y_continuous(sec.axis=sec_axis(~.*4.0026/1000, name="He production as Mass (kg)"))
  }
}
