#' @title deepTimeH2Plot
#'
#' @description
#' Produces a ggplot2 of the cumulative amount of hydrogen produced by samples over the specified geologic time in the deepTimeProd() model.
#'
#' @details
#' Takes in the resulting dataframe from deepTimeProd() function and plots the cumulative amount of hydrogen generated by the sample over the duration of the model. Can plot an optional geom_ribbon() around the min/max of the Monte Carlo model.
#'
#' @param deepTimeProdDF Structured dataframe that is the result of the deepTimeProd() function
#' @param ribbon Optional geom_ribbon() around the min/max of the Monte Carlo model
#'
#' @examples
#' data("monteDataLithCat")
#' df <- monteProd(lithCat,1000)
#' dfTime <- deepTimeProd(df,1,100,1)
#' deepTimeHePlot(dfTime)
#'
#' @export
deepTimeH2Plot <- function(deepTimeProdDF, ribbon=FALSE){
  deepTimeProdDF <- arrange(deepTimeProdDF,desc(time))
  deepTimeProdDF$H2MinProdCum <- ave(deepTimeProdDF$H2MinProd, deepTimeProdDF$Sample, FUN=cumsum)
  deepTimeProdDF$H2MeanProdCum <- ave(deepTimeProdDF$H2MeanProd, deepTimeProdDF$Sample, FUN=cumsum)
  deepTimeProdDF$H2MaxProdCum <- ave(deepTimeProdDF$H2MaxProd, deepTimeProdDF$Sample, FUN=cumsum)
  if (ribbon==FALSE){
    ggplot(deepTimeProdDF) +
      geom_line(mapping=aes(x=time,y=H2MeanProdCum,color=as.factor(Sample))) +
      theme_bw() +
      labs(subtitle="Cumulative H2 production of modeled samples - per km3 of source rock",
           x="Age (Ma)",
           y="H2 production (mols/km3)") +
      scale_x_reverse() +
      scale_y_continuous(sec.axis=sec_axis(~.*2.016/1000, name="Mass (kg)"))
  } else {
    ggplot(deepTimeProdDF) +
      geom_line(mapping=aes(x=time,y=H2MeanProdCum, color=as.factor(Sample))) +
      geom_ribbon(mapping=aes(x=time,ymin=H2MinProdCum,ymax=H2MaxProdCum, fill=as.factor(Sample)),alpha=0.1) +
      theme_bw() +
      labs(subtitle="Cumulative H2 production of modeled samples - per km3 of source rock",
           x="Age (Ma)",
           y="H2 production (mols/km3)") +
      scale_x_reverse() +
      scale_y_continuous(sec.axis=sec_axis(~.*2.016/1000, name="Mass (kg)"))
  }
}
